### ISSUE TITLE
Custom GithubAction and GradlePlugin for lib dependents

### ISSUE THREAD

**Issue by rtc11** [navikt/helseopplysninger#320]
👻  **Describe the problem**
When changes in libs are committed to main, the apps will not automatically build/deploy with these changes.

🤖 **Propose a solution**
* Create a custom Gradle Plugin that locates a libraries dependents (apps that uses the lib)
* Create a Github Action that locates the changes, uses the gradle plugin and triggers a workflow for each app.

👽 **Tell me about the alternatives**
* Gradle have a task buildDependents. This will not work with our docker multi stage setup
* Each app workflow can listen to changes on path `libs/**` (Easiest, but will build when irrelevant libs have changes)
* Each app specifies which libs it uses in their workflow (more difficult to maintain)
 
👾 **Additional context**
Custom gradle task:
```kotlin
@Suppress("LeakingThis")
abstract class DependentsTask : DefaultTask() {
    @get:Input
    abstract val lib: Property<String>

    init {
        lib.convention("UNSPECIFIED")
    }

    @OutputDirectory
    val outDir = File("build/dependents/").also { it.mkdir() }
    private val outFile by lazy {
        File("${outDir.path}/${lib.get()}.txt").also { it.writeText("") }
    }

    @TaskAction
    fun dependents() = when (lib.get()) {
        "UNSPECIFIED" -> logger.warn("task :dependents not run because of missing argument '-Plib=<name-of-lib>'")
        else -> project.subprojects.find { it.name == "apps" }?.subprojects?.forEach(::outputDependents)
    }

    private fun outputDependents(app: Project) {
        val isAppDependentOnLibrary = app.configurations.getByName("testRuntimeClasspath")
            .resolvedConfiguration
            .resolvedArtifacts
            .asSequence()
            .map { it.id.componentIdentifier }
            .filterIsInstance<ProjectComponentIdentifier>()
            .map { it.projectName }
            .any { it == lib.get() }

        if (isAppDependentOnLibrary) {
            println("${lib.get()} is used in ${app.name}")
            outFile.apply {
                appendText(app.name)
                appendText("\n")
            }
        }
    }
}
```

Usage of the gradle task:
Note: we need to extend `clean` task to delete the /build/dependents/ directory. 
```kotlin
tasks {
    register<DependentsTask>("dependents") {
        lib.set(project.properties["lib"] as String?)
    }
    getByName<Delete>("clean") {
        delete("/build")
    }
}
```

build.gradle.kts:
```kotlin
// Might have to include this plugin, based on the implementation:
plugins {
    base
}
```

The action:
Note: this is a workflow POC:
```yaml
on:
  push:
    branches: [main]
    paths:
      - 'libs/**'
      - '!libs/*/test/**'

jobs:
  build-library-dependents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'gradle'

      # Use 'git diff' to locate libs with changes
      # Strip the diff path to get the lib names
      # Keep distinct lib names
      # Iterate over lib nanes with gradle task 'dependents'.
      # This will locate every app that depends on the lib and puts it in a file under /build/depenents/<lib-name>.txt
      - name: Locate changed libs and their dependents
        run: |
          git \
            diff --name-only libs/ | \
            sed -e "s/^libs\///" | \
            cut -f1 -d'/' | \
            sort | uniq | \
            xargs -I '{}' ./gradlew dependents -Plib={}

      - name: Trigger relevant app workflows
        run: |
          cat build/dependents/* | less | sort | uniq | "TRIGGER-WORKFLOW-NAME"

```
